name: Deploy to Vercel

on:
  push:
    branches:
      - master

env:
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - name: Print env variables
        run: echo $VITE_SUPABASE_URL and $VITE_SUPABASE_ANON_KEY
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
